modLoader="javafml"
loaderVersion=""
license=""

[[mods]]
modId=""
version=""
displayName=""
authors=""
description=""
logoFile="logo.png"

[[dependencies.]]
modId="neoforge"
type="required"
versionRange=""
ordering="NONE"
side="BOTH"

[[dependencies.]]
modId="minecraft"
type="required"
versionRange=""
ordering="NONE"
side="BOTH"

[[dependencies.]]
modId="ae2"
type="required"
versionRange=""
ordering="AFTER"
side="BOTH"
